# Generated by Django 4.0.4 on 2022-04-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hku_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueCode', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=2)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('hku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studySafeCore.members')),
                ('venueCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studySafeCore.venues')),
            ],
        ),
    ]
