# Generated by Django 4.0.4 on 2022-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studySafeCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='entry_time',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='records',
            name='exit_time',
        ),
    ]
