# Generated by Django 4.0.4 on 2022-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studySafeCore', '0002_rename_entry_time_records_date_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TaskForceMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='HKUMembers',
        ),
        migrations.AlterField(
            model_name='records',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='venues',
            name='capacity',
            field=models.SmallIntegerField(),
        ),
    ]
