# Generated by Django 4.0.4 on 2022-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studySafeCore', '0003_deviceusers_taskforcemembers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venues',
            name='members',
            field=models.ManyToManyField(through='studySafeCore.Records', to='studySafeCore.hkumembers'),
        ),
    ]
