# Generated by Django 4.0.4 on 2022-04-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studySafeCore', '0004_venues_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='hku_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studySafeCore.hkumembers'),
        ),
    ]
